---
- name: Generate POST data
  set_fact:
    validator_import_post_data: |
      {
        "keystores": {{ item.content | to_json }},
        "passwords": {{ item.passwords | to_json }}
      }

- name: Write API data to file
  copy:
    dest: "/tmp/validator-import-api-data"
    content: "{{ validator_import_post_data }}"
  become: yes

- name: Import validator using API
  community.docker.docker_container:
    command_handling: correct
    name: "validator-import-api-curl"
    user: "2000"
    image: "curlimages/curl:{{ stereum.defaults.versions.curl }}"
    detach: false
    command: |
      curl -X POST {{ api_service_protocol | default("http") }}://stereum-{{ validator_service }}:{{ validator_port }}/eth/v1/keystores
      -H "Content-Type: application/json"
      -H "Authorization: Bearer {{ api_token }}"
      -d "@/validator-import-api-data"
    networks:
      - name: stereum
    volumes:
      - "/tmp/validator-import-api-data:/validator-import-api-data"
  become: yes
  register: validator_import_api_result

- name: Log import result
  debug:
    msg: "{{ validator_import_api_result.container.Output }}"

- name: Remove AIP data file
  ansible.builtin.file:
    path: "/tmp/validator-import-api-data"
    state: absent

- name: Remove docker container
  community.docker.docker_container:
    name: "validator-import-api-curl"
    state: absent

# EOF
