---
#############
# read config
- name: Build service configuration's path
  set_fact:
    stereum_service_config_path: "/etc/stereum/services/{{ validator_service }}.yaml"
- name: Read service's configuration
  slurp:
    src: "{{ stereum_service_config_path }}"
  register: stereum_service_configuration_raw
  become: yes
- name: Read variable
  set_fact:
    stereum_service_configuration: "{{ stereum_service_configuration_raw.content | b64decode | from_yaml }}"
  become: yes

########
# import
- block:
  - name: Prysm - Get validator service's api token
    command: "docker exec -u 0 -w /opt/app/data/wallets stereum-{{ validator_service }} cat auth-token"
    changed_when: false
    register: auth_token
    become: yes
  - name: Get api-token
    set_fact:
      api_token: "{{ auth_token.stdout_lines[1] }}"
  - include_tasks: import.yaml
    vars:
      validator_port: 7500
    loop: "{{ validator_keys }}"
  when: stereum_service_configuration.service == "PrysmValidatorService"

- block:
  - name: Lighthouse - Get validator service's api token
    command: "docker exec -u 0 -w /opt/app/validator/validators stereum-{{ validator_service }} cat api-token.txt"
    changed_when: false
    register: api_token_lh
    become: yes
  - include_tasks: import.yaml
    vars:
      validator_port: 5062
      api_token: "{{ api_token_lh.stdout }}"
    loop: "{{ validator_keys }}"
  when: stereum_service_configuration.service == "LighthouseValidatorService"

- block:
  - name: Nimbus - Get validator service's api token
    command: "docker exec -u 0 -w /opt/app/validators stereum-{{ beacon_service }} cat api-token.txt"
    changed_when: false
    register: api_token_n
    become: yes
  - include_tasks: import.yaml
    vars:
      validator_port: 5052
      api_token: "{{ api_token_n.stdout }}"
      validator_service: "{{ beacon_service }}"
    loop: "{{ validator_keys }}"
  when: stereum_service_configuration.service == "NimbusBeaconService"

- block:
  - name: Teku - Get validator service's api token
    command: "docker exec -u 0 -w /opt/app/data/validator/key-manager stereum-{{ beacon_service }} cat validator-api-bearer"
    changed_when: false
    register: api_token_t
    become: yes
  - include_tasks: import.yaml
    vars:
      validator_port: 5052
      api_token: "{{ api_token_t.stdout }}"
      validator_service: "{{ beacon_service }}"
      api_service_protocol: "--insecure https"
    loop: "{{ validator_keys }}"
  when: stereum_service_configuration.service == "TekuBeaconService"

# EOF
